=== a-l-e-x-d-s-9/plps_verification/Examples/control_graph.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <xs:complexType name="conditions_type">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:choice minOccurs="0" maxOccurs="1">
        <xs:element name="predicate_condition" type="predicate_type" />
        <xs:element name="formula_condition" type="formula_condition_type" />
        <xs:element name="not_condition" type="not_condition_type" />
        <xs:element name="forall_condition" type="forall_condition_type" />
        <xs:element name="exists_condition" type="exists_condition_type" />
        <xs:element name="AND" type="and_or_condition_type" />
        <xs:element name="OR" type="and_or_condition_type" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="and_or_condition_type">
    <xs:sequence minOccurs="2" maxOccurs="unbounded">
      <xs:choice minOccurs="1" maxOccurs="1">
        <xs:element name="predicate_condition" type="predicate_type" />
        <xs:element name="formula_condition" type="formula_condition_type" />
        <xs:element name="not_condition" type="not_condition_type" />
        <xs:element name="forall_condition" type="forall_condition_type" />
        <xs:element name="exists_condition" type="exists_condition_type" />
        <xs:element name="AND" type="and_or_condition_type" />
        <xs:element name="OR" type="and_or_condition_type" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="predicate_type">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="field" type="field_type" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="formula_condition_type">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:element name="expression" type="simple_value_type" />
      <xs:choice minOccurs="1" maxOccurs="1">
        <xs:sequence minOccurs="1" maxOccurs="1">
          <xs:element name="operator">
            <xs:complexType>
              <xs:attribute name="type" type="operator_type" />
            </xs:complexType>
          </xs:element>
          <xs:element name="expression" type="simple_value_type" />
        </xs:sequence>
        <xs:sequence minOccurs="1" maxOccurs="1">
          <xs:element name="inside_range">
            <xs:complexType>
              <xs:sequence minOccurs="1" maxOccurs="1">
                <xs:element name="range" type="range_type" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="key_description" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="simple_value_type">
    <xs:attribute name="value" type="xs:string" use="required" />
  </xs:complexType>

  <xs:simpleType name="operator_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="=" />
      <xs:enumeration value="!=" />
      <xs:enumeration value="less" />
      <xs:enumeration value="less_equal" />
      <xs:enumeration value="greater" />
      <xs:enumeration value="greater_equal" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="not_condition_type">
    <xs:choice minOccurs="1" maxOccurs="1">
      <xs:element name="predicate_condition" type="predicate_type" />
      <xs:element name="forall_condition" type="forall_condition_type" />
      <xs:element name="exists_condition" type="exists_condition_type" />
      <xs:element name="AND" type="and_or_condition_type" />
      <xs:element name="OR" type="and_or_condition_type" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="forall_condition_type">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element name="param">
          <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:choice minOccurs="1" maxOccurs="1">
        <xs:element name="predicate_condition" type="predicate_type" />
        <xs:element name="formula_condition" type="formula_condition_type" />
        <xs:element name="exists_condition" type="exists_condition_type" />
        <xs:element name="not_condition" type="not_condition_type" />
        <xs:element name="AND" type="and_or_condition_type" />
        <xs:element name="OR" type="and_or_condition_type" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="exists_condition_type">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element name="param">
          <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:choice minOccurs="1" maxOccurs="1">
        <xs:element name="predicate_condition" type="predicate_type" />
        <xs:element name="formula_condition" type="formula_condition_type" />
        <xs:element name="forall_condition" type="forall_condition_type" />
        <xs:element name="not_condition" type="not_condition_type" />
        <xs:element name="AND" type="and_or_condition_type" />
        <xs:element name="OR" type="and_or_condition_type" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="field_type">
    <xs:attribute name="value" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="range_type">
    <xs:attribute name="min_value" type="xs:string" use="required" />
    <xs:attribute name="min_inclusive" type="xs:boolean" use="required" />
    <xs:attribute name="max_value" type="xs:string" use="required" />
    <xs:attribute name="max_inclusive" type="xs:boolean" use="required" />
  </xs:complexType>





<xs:simpleType name="type_start_policy">
  <xs:restriction base="xs:string">
    <xs:enumeration value="all_predecessor_done" />
    <xs:enumeration value="any_predecessor_done" />
  </xs:restriction>
</xs:simpleType>
  
<xs:element name="control_graph">
  <xs:complexType>
    <xs:sequence>
      
      <xs:element name="root">
        <xs:complexType>
          <xs:attribute name="root_name" type="xs:string"   use="required"/>
        </xs:complexType>
      </xs:element>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        
        <xs:element name="node_probability">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="probability_for_successor_node" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="update" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="formula_condition" type="formula_condition_type" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="probability"  type="xs:string"   use="required"/>
                  <xs:attribute name="node_name"    type="xs:string"   use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="node_name"      type="xs:ID"                use="required"/>
            <xs:attribute name="start_policy"   type="type_start_policy"    use="required"/>
            <xs:attribute name="wait_time"      type="xs:string"            use="optional"/>
          </xs:complexType>
        </xs:element>
                
        <xs:element name="node_concurrent">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="update" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="formula_condition" type="formula_condition_type" minOccurs="1" maxOccurs="1" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="run_node" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="node_name"   type="xs:string"   use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="node_name"      type="xs:ID"                use="required"/>
            <xs:attribute name="start_policy"   type="type_start_policy"    use="required"/>
            <xs:attribute name="wait_time"      type="xs:string"            use="optional"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="node_sequential">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="run_plp" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="update" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="formula_condition" type="formula_condition_type" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="plp_name"   type="xs:string"   use="required"/>
                  <xs:attribute name="wait_time"  type="xs:string"   use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="node_name"      type="xs:ID"                use="required"/>
            <xs:attribute name="start_policy"   type="type_start_policy"    use="required"/>
            <xs:attribute name="next_node_name" type="xs:string"            use="optional"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="node_condition">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="run_node" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="preconditions" type="conditions_type" minOccurs="1" maxOccurs="1" />
                    <xs:element name="update" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="formula_condition" type="formula_condition_type" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="node_name"    type="xs:string"   use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="node_name"             type="xs:ID"                use="required"/>
            <xs:attribute name="start_policy"   type="type_start_policy"    use="required"/>
            <xs:attribute name="wait_time"      type="xs:string"            use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== a-l-e-x-d-s-9/plps_verification/Examples/example_comprehensive_test/control_graph.xml
<?xml version="1.0" encoding="UTF-8"?>

<control_graph
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="control_graph.xsd">

<root root_name="node_probability_00000000"/>

<node_probability node_name="node_probability_00000000" start_policy="any_predecessor_done" wait_time="0">
	<probability_for_successor_node probability="0.5" node_name="node_concurrent_00000001"/>
	<probability_for_successor_node probability="0.5" node_name="node_concurrent_00000002"/>
</node_probability>
<node_concurrent   node_name="node_concurrent_00000001" start_policy="any_predecessor_done">
	<run_node node_name="node_sequential_maintain_00000003"/>
	<run_node node_name="node_sequential_observe_00000005"/>
</node_concurrent>
<node_sequential   node_name="node_sequential_maintain_00000003" start_policy="any_predecessor_done" next_node_name="">
	<run_plp plp_name="maintain_00000004" wait_time="0"></run_plp>
</node_sequential>
<node_sequential   node_name="node_sequential_observe_00000005" start_policy="any_predecessor_done" next_node_name="node_condition_00000007">
	<run_plp plp_name="observe_00000006" wait_time="0"></run_plp>
</node_sequential>
<node_condition   node_name="node_condition_00000007" start_policy="any_predecessor_done">
	<run_node node_name="node_sequential_achieve_true_00000008">
		<preconditions>
			<formula_condition key_description="true == observe_goal_00000006">
				<expression value="_observe_00000006_observe_goal_00000006" />
				<operator type="="/>
				<expression value="TRUE" />
			</formula_condition>
		</preconditions>
	</run_node>
	<run_node node_name="node_sequential_achieve_false_00000009">
		<preconditions>
			<formula_condition key_description="false == observe_goal_00000006">
				<expression value="_observe_00000006_observe_goal_00000006" />
				<operator type="="/>
				<expression value="FALSE" />
			</formula_condition>
		</preconditions>
	</run_node>
</node_condition>
<node_sequential   node_name="node_sequential_achieve_true_00000008" start_policy="any_predecessor_done" next_node_name="">
	<run_plp plp_name="achieve_true_00000010" wait_time="0"></run_plp>
</node_sequential>
<node_sequential   node_name="node_sequential_achieve_false_00000009" start_policy="any_predecessor_done" next_node_name="">
	<run_plp plp_name="achieve_false_00000011" wait_time="0"></run_plp>
</node_sequential><node_concurrent   node_name="node_concurrent_00000002" start_policy="any_predecessor_done">
	<run_node node_name="node_sequential_maintain_00000012"/>
	<run_node node_name="node_sequential_observe_00000014"/>
</node_concurrent>
<node_sequential   node_name="node_sequential_maintain_00000012" start_policy="any_predecessor_done" next_node_name="">
	<run_plp plp_name="maintain_00000013" wait_time="0"></run_plp>
</node_sequential>
<node_sequential   node_name="node_sequential_observe_00000014" start_policy="any_predecessor_done" next_node_name="node_condition_00000016">
	<run_plp plp_name="observe_00000015" wait_time="0"></run_plp>
</node_sequential>
<node_condition   node_name="node_condition_00000016" start_policy="any_predecessor_done">
	<run_node node_name="node_sequential_achieve_true_00000017">
		<preconditions>
			<formula_condition key_description="true == observe_goal_00000015">
				<expression value="_observe_00000015_observe_goal_00000015" />
				<operator type="="/>
				<expression value="TRUE" />
			</formula_condition>
		</preconditions>
	</run_node>
	<run_node node_name="node_sequential_achieve_false_00000018">
		<preconditions>
			<formula_condition key_description="false == observe_goal_00000015">
				<expression value="_observe_00000015_observe_goal_00000015" />
				<operator type="="/>
				<expression value="FALSE" />
			</formula_condition>
		</preconditions>
	</run_node>
</node_condition>
<node_sequential   node_name="node_sequential_achieve_true_00000017" start_policy="any_predecessor_done" next_node_name="">
	<run_plp plp_name="achieve_true_00000019" wait_time="0"></run_plp>
</node_sequential>
<node_sequential   node_name="node_sequential_achieve_false_00000018" start_policy="any_predecessor_done" next_node_name="">
	<run_plp plp_name="achieve_false_00000020" wait_time="0"></run_plp>
</node_sequential></control_graph>

=== a-l-e-x-d-s-9/plps_verification/Examples/example_comprehensive_test/control_graph_basic.xml
<?xml version="1.0" encoding="UTF-8"?>

<control_graph
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="control_graph.xsd">

<root root_name="node_concurrent_"/>
<node_concurrent   node_name="node_concurrent_" start_policy="any_predecessor_done">
    <run_node node_name="node_sequential_maintain_"/>
    <run_node node_name="node_sequential_observe_"/>
</node_concurrent><node_sequential   node_name="node_sequential_maintain_" start_policy="any_predecessor_done" next_node_name="">
    <run_plp plp_name="maintain_" wait_time="0"></run_plp>
</node_sequential>
<node_sequential   node_name="node_sequential_observe_" start_policy="any_predecessor_done" next_node_name="node_condition_">
    <run_plp plp_name="observe_" wait_time="0"></run_plp>
</node_sequential>
<node_condition   node_name="node_condition_" start_policy="any_predecessor_done">
    <run_node node_name="node_sequential_achieve_true_">
        <preconditions>
            <formula_condition key_description="true == observe_goal_">
              <expression value="_observe__observe_goal_" />
              <operator type="="/>
              <expression value="TRUE" />
            </formula_condition>
        </preconditions>
    </run_node>
    <run_node node_name="node_sequential_achieve_false_">
        <preconditions>
            <formula_condition key_description="false == observe_goal_">
              <expression value="_observe__observe_goal_" />
              <operator type="="/>
              <expression value="FALSE" />
            </formula_condition>
        </preconditions>
    </run_node>
</node_condition>
<node_sequential   node_name="node_sequential_achieve_true_" start_policy="any_predecessor_done" next_node_name="">
    <run_plp plp_name="achieve_true_" wait_time="0"></run_plp>
</node_sequential>
<node_sequential   node_name="node_sequential_achieve_false_" start_policy="any_predecessor_done" next_node_name="">
    <run_plp plp_name="achieve_false_" wait_time="0"></run_plp>
</node_sequential>
</control_graph>

=== a-l-e-x-d-s-9/plps_verification/Examples/example_00/control_graph.xml
<?xml version="1.0" encoding="UTF-8"?>

<control_graph
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="control_graph.xsd">

<root root_name="node_probability_1"/>


<node_probability   node_name="node_probability_1" start_policy="any_predecessor_done" wait_time="1">
  <probability_for_successor_node probability="0.1" node_name="node_probability_2">
    <update>
      <formula_condition key_description="update variables">
        <expression value="distance_to_goal" />
        <operator type="="/>
        <expression value="2" />
      </formula_condition>
    </update>
    <update>
      <formula_condition key_description="update variables">
        <expression value="tmp_var" />
        <operator type="="/>
        <expression value="11" />
      </formula_condition>
    </update>
  </probability_for_successor_node>
  <probability_for_successor_node probability="0.8" node_name="node_probability_3"/>
  <probability_for_successor_node probability="0.03" node_name="node_probability_3"/>
  <probability_for_successor_node probability="0.03" node_name="node_probability_3"/>
  <probability_for_successor_node probability="0.04" node_name="node_probability_3"/>
</node_probability>

<node_probability   node_name="node_probability_2" start_policy="any_predecessor_done" wait_time="2">
    <probability_for_successor_node probability="1" node_name="node_probability_4"/>
</node_probability>
<node_probability   node_name="node_probability_3" start_policy="any_predecessor_done" wait_time="3">
    <probability_for_successor_node probability="1" node_name="node_probability_4"/>
</node_probability>
<node_probability   node_name="node_probability_4" start_policy="any_predecessor_done" wait_time="4">
    <probability_for_successor_node probability="1" node_name="node_concurrent_1"/>
</node_probability>

<node_concurrent   node_name="node_concurrent_1" start_policy="any_predecessor_done" wait_time="3">
    <run_node node_name="node_concurrent_2"/>
    <run_node node_name="node_concurrent_3"/>
    <run_node node_name="node_concurrent_4"/>
</node_concurrent>
<node_concurrent   node_name="node_concurrent_2" start_policy="all_predecessor_done" wait_time="2">
</node_concurrent>
<node_concurrent   node_name="node_concurrent_3" start_policy="all_predecessor_done" wait_time="5">
</node_concurrent>
<node_concurrent   node_name="node_concurrent_4" start_policy="all_predecessor_done" wait_time="1">
    <update>
      <formula_condition key_description="update variables">
        <expression value="energy_consumed" />
        <operator type="="/>
        <expression value="3" />
      </formula_condition>
    </update>
    <run_node node_name="node_sequential_1"/>
    <run_node node_name="node_sequential_2"/>
</node_concurrent>

<node_sequential   node_name="node_sequential_1" start_policy="any_predecessor_done" next_node_name="node_condition_1">
    <run_plp plp_name="maintain_direction_on_map" wait_time="4">
        <update>
          <formula_condition key_description="update variables">
            <expression value="distance_to_goal" />
            <operator type="="/>
            <expression value="9" />
          </formula_condition>
        </update>
        <update>
          <formula_condition key_description="update variables">
            <expression value="runtime_given_path_length" />
            <operator type="="/>
            <expression value="3" />
          </formula_condition>
        </update>
        <update>
          <formula_condition key_description="free_path">
            <expression value="_maintain_direction_on_map_path_free" />
            <operator type="=" />
            <expression value="TRUE" />
          </formula_condition>
        </update>
    </run_plp>
    <!--run_plp plp_name="detect_wall" wait_time="0">
        <update>
          <formula_condition key_description="update variables">
            <expression value="distance_to_goal" />
            <operator type="="/>
            <expression value="8" />
          </formula_condition>
        </update>
        <update>
          <formula_condition key_description="update variables">
            <expression value="runtime_given_path_length" />
            <operator type="="/>
            <expression value="2" />
          </formula_condition>
        </update>
        <update>
          <formula_condition key_description="free_path">
            <expression value="_maintain_direction_on_map_path_free" />
            <operator type="=" />
            <expression value="TRUE" />
          </formula_condition>
        </update>
    </run_plp-->
</node_sequential>

<node_sequential   node_name="node_sequential_2" start_policy="any_predecessor_done" next_node_name="node_condition_1">
    <run_plp plp_name="achieve_walk_given_distance" wait_time="2">
        <update>
          <formula_condition key_description="update variables">
            <expression value="distance_to_goal" />
            <operator type="="/>
            <expression value="9" />
          </formula_condition>
        </update>
        <update>
          <formula_condition key_description="update variables">
            <expression value="runtime_given_path_length" />
            <operator type="="/>
            <expression value="3" />
          </formula_condition>
        </update>
        <update>
          <formula_condition key_description="free_path">
            <expression value="_maintain_direction_on_map_path_free" />
            <operator type="=" />
            <expression value="TRUE" />
          </formula_condition>
        </update>
    </run_plp>
    <run_plp plp_name="observe_gateway" wait_time="1">
        <update>
          <formula_condition key_description="update variables">
            <expression value="distance_to_goal" />
            <operator type="="/>
            <expression value="8" />
          </formula_condition>
        </update>
        <update>
          <formula_condition key_description="update variables">
            <expression value="runtime_given_path_length" />
            <operator type="="/>
            <expression value="2" />
          </formula_condition>
        </update>
        <update>
          <formula_condition key_description="free_path">
            <expression value="_maintain_direction_on_map_path_free" />
            <operator type="=" />
            <expression value="TRUE" />
          </formula_condition>
        </update>
    </run_plp>
</node_sequential>

<node_condition   node_name="node_condition_1" start_policy="all_predecessor_done" wait_time="1">
    <run_node node_name="node_condition_2">
        <preconditions>
            <formula_condition key_description="condition test">
              <expression value="energy_consumed" />
              <operator type="="/>
              <expression value="3" />
            </formula_condition>
            <formula_condition key_description="update variables">
              <expression value="tmp_var" />
              <operator type="="/>
              <expression value="11" />
            </formula_condition>
        </preconditions>
        <update>
          <formula_condition key_description="update variables">
            <expression value="distance_to_goal" />
            <operator type="="/>
            <expression value="1" />
          </formula_condition>
        </update>
    </run_node>
    <run_node node_name="node_condition_2">
        <preconditions>
            <OR>
                <formula_condition key_description="condition test">
                  <expression value="energy_consumed" />
                  <operator type="="/>
                  <expression value="3" />
                </formula_condition>
                <formula_condition key_description="update variables">
                  <expression value="tmp_var" />
                  <operator type="="/>
                  <expression value="12" />
                </formula_condition>
            </OR>
        </preconditions>
        <update>
          <formula_condition key_description="update variables">
            <expression value="vehicle_off_road" />
            <operator type="="/>
            <expression value="1" />
          </formula_condition>
        </update>
        <update>
          <formula_condition key_description="update variables">
            <expression value="distance_to_goal" />
            <operator type="="/>
            <expression value="1" />
          </formula_condition>
        </update>
    </run_node>
</node_condition>


<node_condition   node_name="node_condition_2" start_policy="all_predecessor_done" wait_time="1">
</node_condition>



</control_graph>
