=== a-l-e-x-d-s-9/plps_verification/Examples/control_graph.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <xs:complexType name="conditions_type">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:choice minOccurs="0" maxOccurs="1">
        <xs:element name="predicate_condition" type="predicate_type" />
        <xs:element name="formula_condition" type="formula_condition_type" />
        <xs:element name="not_condition" type="not_condition_type" />
        <xs:element name="forall_condition" type="forall_condition_type" />
        <xs:element name="exists_condition" type="exists_condition_type" />
        <xs:element name="AND" type="and_or_condition_type" />
        <xs:element name="OR" type="and_or_condition_type" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="and_or_condition_type">
    <xs:sequence minOccurs="2" maxOccurs="unbounded">
      <xs:choice minOccurs="1" maxOccurs="1">
        <xs:element name="predicate_condition" type="predicate_type" />
        <xs:element name="formula_condition" type="formula_condition_type" />
        <xs:element name="not_condition" type="not_condition_type" />
        <xs:element name="forall_condition" type="forall_condition_type" />
        <xs:element name="exists_condition" type="exists_condition_type" />
        <xs:element name="AND" type="and_or_condition_type" />
        <xs:element name="OR" type="and_or_condition_type" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="predicate_type">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="field" type="field_type" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="formula_condition_type">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:element name="expression" type="simple_value_type" />
      <xs:choice minOccurs="1" maxOccurs="1">
        <xs:sequence minOccurs="1" maxOccurs="1">
          <xs:element name="operator">
            <xs:complexType>
              <xs:attribute name="type" type="operator_type" />
            </xs:complexType>
          </xs:element>
          <xs:element name="expression" type="simple_value_type" />
        </xs:sequence>
        <xs:sequence minOccurs="1" maxOccurs="1">
          <xs:element name="inside_range">
            <xs:complexType>
              <xs:sequence minOccurs="1" maxOccurs="1">
                <xs:element name="range" type="range_type" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="key_description" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="simple_value_type">
    <xs:attribute name="value" type="xs:string" use="required" />
  </xs:complexType>

  <xs:simpleType name="operator_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="=" />
      <xs:enumeration value="!=" />
      <xs:enumeration value="less" />
      <xs:enumeration value="less_equal" />
      <xs:enumeration value="greater" />
      <xs:enumeration value="greater_equal" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="not_condition_type">
    <xs:choice minOccurs="1" maxOccurs="1">
      <xs:element name="predicate_condition" type="predicate_type" />
      <xs:element name="forall_condition" type="forall_condition_type" />
      <xs:element name="exists_condition" type="exists_condition_type" />
      <xs:element name="AND" type="and_or_condition_type" />
      <xs:element name="OR" type="and_or_condition_type" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="forall_condition_type">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element name="param">
          <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:choice minOccurs="1" maxOccurs="1">
        <xs:element name="predicate_condition" type="predicate_type" />
        <xs:element name="formula_condition" type="formula_condition_type" />
        <xs:element name="exists_condition" type="exists_condition_type" />
        <xs:element name="not_condition" type="not_condition_type" />
        <xs:element name="AND" type="and_or_condition_type" />
        <xs:element name="OR" type="and_or_condition_type" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="exists_condition_type">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element name="param">
          <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:choice minOccurs="1" maxOccurs="1">
        <xs:element name="predicate_condition" type="predicate_type" />
        <xs:element name="formula_condition" type="formula_condition_type" />
        <xs:element name="forall_condition" type="forall_condition_type" />
        <xs:element name="not_condition" type="not_condition_type" />
        <xs:element name="AND" type="and_or_condition_type" />
        <xs:element name="OR" type="and_or_condition_type" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="field_type">
    <xs:attribute name="value" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="range_type">
    <xs:attribute name="min_value" type="xs:string" use="required" />
    <xs:attribute name="min_inclusive" type="xs:boolean" use="required" />
    <xs:attribute name="max_value" type="xs:string" use="required" />
    <xs:attribute name="max_inclusive" type="xs:boolean" use="required" />
  </xs:complexType>





<xs:simpleType name="type_start_policy">
  <xs:restriction base="xs:string">
    <xs:enumeration value="all_predecessor_done" />
    <xs:enumeration value="any_predecessor_done" />
  </xs:restriction>
</xs:simpleType>
  
<xs:element name="control_graph">
  <xs:complexType>
    <xs:sequence>
      
      <xs:element name="root">
        <xs:complexType>
          <xs:attribute name="root_name" type="xs:string"   use="required"/>
        </xs:complexType>
      </xs:element>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        
        <xs:element name="node_probability">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="probability_for_successor_node" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="update" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="formula_condition" type="formula_condition_type" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="probability"  type="xs:string"   use="required"/>
                  <xs:attribute name="node_name"    type="xs:string"   use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="node_name"      type="xs:ID"                use="required"/>
            <xs:attribute name="start_policy"   type="type_start_policy"    use="required"/>
            <xs:attribute name="wait_time"      type="xs:string"            use="optional"/>
          </xs:complexType>
        </xs:element>
                
        <xs:element name="node_concurrent">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="update" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="formula_condition" type="formula_condition_type" minOccurs="1" maxOccurs="1" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="run_node" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="node_name"   type="xs:string"   use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="node_name"      type="xs:ID"                use="required"/>
            <xs:attribute name="start_policy"   type="type_start_policy"    use="required"/>
            <xs:attribute name="wait_time"      type="xs:string"            use="optional"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="node_sequential">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="run_plp" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="update" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="formula_condition" type="formula_condition_type" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="plp_name"   type="xs:string"   use="required"/>
                  <xs:attribute name="wait_time"  type="xs:string"   use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="node_name"      type="xs:ID"                use="required"/>
            <xs:attribute name="start_policy"   type="type_start_policy"    use="required"/>
            <xs:attribute name="next_node_name" type="xs:string"            use="optional"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="node_condition">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="run_node" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="preconditions" type="conditions_type" minOccurs="1" maxOccurs="1" />
                    <xs:element name="update" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="formula_condition" type="formula_condition_type" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="node_name"    type="xs:string"   use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="node_name"             type="xs:ID"                use="required"/>
            <xs:attribute name="start_policy"   type="type_start_policy"    use="required"/>
            <xs:attribute name="wait_time"      type="xs:string"            use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== a-l-e-x-d-s-9/plps_verification/Examples/example_test/control_graph_backup.xml
<?xml version="1.0" encoding="UTF-8"?>

<control_graph
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="control_graph.xsd">

<root root_name="node_sequential_1"/>

<node_sequential   node_name="node_sequential_1" start_policy="any_predecessor_done" next_node_name="">
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
    <run_plp plp_name="move_forward" wait_time="0"></run_plp>
</node_sequential>


</control_graph>

=== a-l-e-x-d-s-9/plps_verification/Examples/example_loops/condition_control_graph.xml
<?xml version="1.0" encoding="UTF-8"?>

<control_graph
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="control_graph.xsd">

<root root_name="node_sequential_start"/>

<node_sequential   node_name="node_sequential_start" start_policy="any_predecessor_done" next_node_name="node_concurrent_hold_and_move">
    <run_plp plp_name="achieve_move_to">
        <update>
          <formula_condition key_description="update variables">
            <expression value="_achieve_move_to_destination" />
            <operator type="="/>
            <expression value="at_a_key" />
          </formula_condition>
        </update>
    </run_plp>
    <run_plp plp_name="achieve_key_take">
    </run_plp>
</node_sequential>

<node_concurrent   node_name="node_concurrent_hold_and_move" start_policy="any_predecessor_done">
    <run_node node_name="node_sequential_key_holding"/>
    <run_node node_name="node_sequential_move_to_door"/>
</node_concurrent>

<node_sequential   node_name="node_sequential_key_holding" start_policy="any_predecessor_done" next_node_name="">
    <run_plp plp_name="maintain_key_hold">
    </run_plp>
</node_sequential>

<node_sequential   node_name="node_sequential_move_to_door" start_policy="any_predecessor_done" next_node_name="node_condition_decide_after_is_open">
    <run_plp plp_name="achieve_move_to">
        <update>
          <formula_condition key_description="update variables">
            <expression value="_achieve_move_to_destination" />
            <operator type="="/>
            <expression value="at_a_doorway" />
          </formula_condition>
        </update>
    </run_plp>
    <run_plp plp_name="observe_is_door_open">
    </run_plp>
</node_sequential>

<node_condition   node_name="node_condition_decide_after_is_open" start_policy="any_predecessor_done">
    <run_node node_name="node_sequential_move_to_target">
        <preconditions>
            <formula_condition key_description="true == door_is_open">
              <expression value="_observe_is_door_open_door_is_open" />
              <operator type="="/>
              <expression value="TRUE" />
            </formula_condition>
        </preconditions>
    </run_node>
    <run_node node_name="node_sequential_is_door_locked">
        <preconditions>
            <formula_condition key_description="false == door_is_open">
              <expression value="_observe_is_door_open_door_is_open" />
              <operator type="="/>
              <expression value="FALSE" />
            </formula_condition>
        </preconditions>
    </run_node>
</node_condition>

<node_sequential   node_name="node_sequential_is_door_locked" start_policy="any_predecessor_done" next_node_name="node_condition_decide_after_is_locked">
    <run_plp plp_name="observe_is_door_locked">
    </run_plp>
</node_sequential>

<node_condition   node_name="node_condition_decide_after_is_locked" start_policy="any_predecessor_done">
    <run_node node_name="node_sequential_door_unlock">
        <preconditions>
            <formula_condition key_description="true == door_is_locked">
              <expression value="_observe_is_door_locked_door_is_locked" />
              <operator type="="/>
              <expression value="TRUE" />
            </formula_condition>
        </preconditions>
    </run_node>
    <run_node node_name="node_sequential_door_open">
        <preconditions>
            <formula_condition key_description="false == door_is_locked">
              <expression value="_observe_is_door_locked_door_is_locked" />
              <operator type="="/>
              <expression value="FALSE" />
            </formula_condition>
        </preconditions>
    </run_node>
</node_condition>

<node_sequential   node_name="node_sequential_door_unlock" start_policy="any_predecessor_done" next_node_name="node_sequential_door_open">
    <run_plp plp_name="achieve_door_unlock">
    </run_plp>
</node_sequential>

<node_sequential   node_name="node_sequential_door_open" start_policy="any_predecessor_done" next_node_name="node_sequential_move_to_target">
    <run_plp plp_name="achieve_door_open">
    </run_plp>
</node_sequential>


<node_sequential   node_name="node_sequential_move_to_target" start_policy="any_predecessor_done" next_node_name="">
    <run_plp plp_name="achieve_move_to">
        <update>
          <formula_condition key_description="move through doorway">
            <expression value="_achieve_move_to_destination" />
            <operator type="="/>
            <expression value="at_b_doorway" />
          </formula_condition>
        </update>
    </run_plp>
    <run_plp plp_name="achieve_move_to">
        <update>
          <formula_condition key_description="move through doorway">
            <expression value="_achieve_move_to_destination" />
            <operator type="="/>
            <expression value="at_b_target" />
          </formula_condition>
        </update>
    </run_plp>
</node_sequential>

</control_graph>

=== a-l-e-x-d-s-9/plps_verification/Examples/example_00/control_graph_test_2_maintains.xml
<?xml version="1.0" encoding="UTF-8"?>

<control_graph
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="control_graph.xsd">

<root root_name="node_concurrent_1"/>

<node_concurrent   node_name="node_concurrent_1" start_policy="any_predecessor_done" wait_time="3">
    <update>
        <formula_condition key_description="free_path">
          <expression value="_maintain_direction_on_map_2_param_path_free" />
          <operator type="=" />
          <expression value="TRUE" />
        </formula_condition>
    </update>
    <update>
        <formula_condition key_description="free_path">
          <expression value="_maintain_direction_on_map_param_path_free" />
          <operator type="=" />
          <expression value="TRUE" />
        </formula_condition>
    </update>
    <run_node node_name="node_sequential_1"/>
    <run_node node_name="node_sequential_2"/>
</node_concurrent>

<node_sequential   node_name="node_sequential_1" start_policy="any_predecessor_done" >
    <run_plp plp_name="maintain_direction_on_map" wait_time="1"></run_plp>
</node_sequential>

<node_sequential   node_name="node_sequential_2" start_policy="any_predecessor_done">
    <run_plp plp_name="maintain_direction_on_map_2" wait_time="1"></run_plp>
</node_sequential>

</control_graph>

=== a-l-e-x-d-s-9/plps_verification/Examples/example_02/control_graph.xml
<?xml version="1.0" encoding="UTF-8"?>

<control_graph
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="control_graph.xsd">

<root root_name="node_sequential_start"/>

<node_sequential   node_name="node_sequential_start" start_policy="any_predecessor_done" next_node_name="node_concurrent_1">
    <run_plp plp_name="achieve_move_to">
        <update>
          <formula_condition key_description="update variables">
            <expression value="_achieve_move_to_destination" />
            <operator type="="/>
            <expression value="at_a_key" />
          </formula_condition>
        </update>
    </run_plp>
    <run_plp plp_name="achieve_key_take" wait_time="1">
    </run_plp>
</node_sequential>

<node_concurrent   node_name="node_concurrent_1" start_policy="any_predecessor_done">
    <run_node node_name="node_sequential_key_holding"/>
    <run_node node_name="node_sequential_move_to_door"/>
</node_concurrent>

<node_sequential   node_name="node_sequential_key_holding" start_policy="any_predecessor_done" next_node_name="">
    <run_plp plp_name="maintain_key_hold">
    </run_plp>
</node_sequential>

<node_sequential   node_name="node_sequential_move_to_door" start_policy="any_predecessor_done" next_node_name="">
    <run_plp plp_name="achieve_move_to">
        <update>
          <formula_condition key_description="update variables">
            <expression value="_achieve_move_to_destination" />
            <operator type="="/>
            <expression value="at_a_key" />
          </formula_condition>
        </update>
    </run_plp>
    <run_plp plp_name="observe_is_door_open">
    </run_plp>
</node_sequential>

</control_graph>

=== a-l-e-x-d-s-9/plps_verification/Examples/example_test/control_graph.xml
<?xml version="1.0" encoding="UTF-8"?>

<control_graph
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="control_graph.xsd">

<root root_name="node_sequential_00001"/><node_sequential   node_name="node_sequential_00001" start_policy="any_predecessor_done" next_node_name="node_sequential_00002">
    <run_plp plp_name="move_forward_00001" wait_time="0"></run_plp>
</node_sequential>
<node_sequential   node_name="node_sequential_00002" start_policy="any_predecessor_done" next_node_name="node_sequential_00003">
    <run_plp plp_name="move_forward_00002" wait_time="0"></run_plp>
</node_sequential>
<node_sequential   node_name="node_sequential_00003" start_policy="any_predecessor_done" next_node_name="node_sequential_00004">
    <run_plp plp_name="move_forward_00003" wait_time="0"></run_plp>
</node_sequential>
<node_sequential   node_name="node_sequential_00004" start_policy="any_predecessor_done" next_node_name="node_sequential_00005">
    <run_plp plp_name="move_forward_00004" wait_time="0"></run_plp>
</node_sequential>
<node_sequential   node_name="node_sequential_00005" start_policy="any_predecessor_done" next_node_name="node_sequential_00006">
    <run_plp plp_name="move_forward_00005" wait_time="0"></run_plp>
</node_sequential>
<node_sequential   node_name="node_sequential_00006" start_policy="any_predecessor_done" next_node_name="node_sequential_00007">
    <run_plp plp_name="move_forward_00006" wait_time="0"></run_plp>
</node_sequential>
<node_sequential   node_name="node_sequential_00007" start_policy="any_predecessor_done" next_node_name="node_sequential_00008">
    <run_plp plp_name="move_forward_00007" wait_time="0"></run_plp>
</node_sequential>
<node_sequential   node_name="node_sequential_00008" start_policy="any_predecessor_done" next_node_name="node_sequential_00009">
    <run_plp plp_name="move_forward_00008" wait_time="0"></run_plp>
</node_sequential>
<node_sequential   node_name="node_sequential_00009" start_policy="any_predecessor_done" next_node_name="node_sequential_00010">
    <run_plp plp_name="move_forward_00009" wait_time="0"></run_plp>
</node_sequential>
<node_sequential   node_name="node_sequential_00010" start_policy="any_predecessor_done" next_node_name="">
    <run_plp plp_name="move_forward_00010" wait_time="0"></run_plp>
</node_sequential>
</control_graph>
